apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-blue
  labels:
    app: podinfo
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
      version: blue
  template:
    metadata:
      labels:
        app: podinfo
        version: blue
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        args: 
         - "--datadir=/app/data"
        securityContext:  # Stellen Sie sicher, dass die Gruppe Zugriff auf das Volume hat
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 9898
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: podinfo-storage  # Mount the persistent volume
          mountPath: /app/data   # Container path to store the data
      volumes:
      - name: podinfo-storage
        persistentVolumeClaim:
          claimName: podinfo-pvc
      securityContext:
        fsGroup: 1000  # Stellen Sie sicher, dass die Gruppe Zugriff auf das Volume hat
        runAsUser: 1000
        runAsGroup: 1000