apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lesen
  namespace: wer-das-liest-kann-lesen
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: engelhatt.k8s.schoeppi5.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port:
              number: 80