apiVersion: v1
kind: PersistentVolume
metadata:
  name: podinfo-pv
spec:
  capacity:
    storage: 10Gi   # Der Speicherplatz, der für den Pod verfügbar ist
  accessModes:
    - ReadWriteOnce  # Nur ein Pod kann gleichzeitig darauf zugreifen
  persistentVolumeReclaimPolicy: Retain  # Behält das Volume bei Pod-Löschung
  hostPath:  # Verwenden eines lokalen Speicherorts auf dem Node
    path: /mnt/data/podinfo
